(module
  (memory 1)
  (data (i32.const 0) "abcdefgh")
  (data (i32.const 0xfff8) "abcdefgh")

  (func (export "i32.load") (param $a i32) (result i32)
    (i32.load (local.get $a))
  )
  (func (export "i64.load") (param $a i32) (result i64)
    (i64.load (local.get $a))
  )
  (func (export "f32.load") (param $a i32) (result f32)
    (f32.load (local.get $a))
  )
  (func (export "f64.load") (param $a i32) (result f64)
    (f64.load (local.get $a))
  )
  (func (export "i32.load8_s") (param $a i32) (result i32)
    (i32.load8_s (local.get $a))
  )
  (func (export "i32.load8_u") (param $a i32) (result i32)
    (i32.load8_u (local.get $a))
  )
  (func (export "i32.load16_s") (param $a i32) (result i32)
    (i32.load16_s (local.get $a))
  )
  (func (export "i32.load16_u") (param $a i32) (result i32)
    (i32.load16_u (local.get $a))
  )
  (func (export "i64.load8_s") (param $a i32) (result i64)
    (i64.load8_s (local.get $a))
  )
  (func (export "i64.load8_u") (param $a i32) (result i64)
    (i64.load8_u (local.get $a))
  )
  (func (export "i64.load16_s") (param $a i32) (result i64)
    (i64.load16_s (local.get $a))
  )
  (func (export "i64.load16_u") (param $a i32) (result i64)
    (i64.load16_u (local.get $a))
  )
  (func (export "i64.load32_s") (param $a i32) (result i64)
    (i64.load32_s (local.get $a))
  )
  (func (export "i64.load32_u") (param $a i32) (result i64)
    (i64.load32_u (local.get $a))
  )
  (func (export "i32.store") (param $a i32) (param $v i32)
    (i32.store (local.get $a) (local.get $v))
  )
  (func (export "i64.store") (param $a i32) (param $v i64)
    (i64.store (local.get $a) (local.get $v))
  )
  (func (export "f32.store") (param $a i32) (param $v f32)
    (f32.store (local.get $a) (local.get $v))
  )
  (func (export "f64.store") (param $a i32) (param $v f64)
    (f64.store (local.get $a) (local.get $v))
  )
  (func (export "i32.store8") (param $a i32) (param $v i32)
    (i32.store8 (local.get $a) (local.get $v))
  )
  (func (export "i32.store16") (param $a i32) (param $v i32)
    (i32.store16 (local.get $a) (local.get $v))
  )
  (func (export "i64.store8") (param $a i32) (param $v i64)
    (i64.store8 (local.get $a) (local.get $v))
  )
  (func (export "i64.store16") (param $a i32) (param $v i64)
    (i64.store16 (local.get $a) (local.get $v))
  )
  (func (export "i64.store32") (param $a i32) (param $v i64)
    (i64.store32 (local.get $a) (local.get $v))
  )
)
