(module
  (@a)
  (@0)
  (@aas-3!@$d-@#4)
  (@@) (@$) (@+) (@0) (@.) (@!$@#$23414@#$)
  (@"a")
  (@" @ asd\2a 045 \" fdaf \t \u{45}")

  (@a x y z)
  (@a x-y $yz "aa" -2 0.3 0x3)
  (@a x-y$yz"aa"-2)
  (@a block func module i32.add)
  (@a 0x 8q 0xfa #4g0-.@f#^&@#$*0sf -- @#)
  (@a , ; ] [ }} }x{ ({) ,{{};}] ;)
  (@a (bla) () (5-g) ("aa" a) ($x) (bla bla) (x (y)) ")" "(" x")"y)
  (@a @ @x (@x) (@x y) (@) (@ x) (@(@(@(@)))))
  (@a (;bla;) (; ) ;)
    ;; bla)
    ;; bla (@x
  )
)
